name: LillyFetch
version: '1.0.0'
main: net.retrolilly.lillyFetch.LillyFetch

commands:
  neofetch:
    description: Display system fetch tool output in-game
    usage: /neofetch [simple]
    aliases: [fastfetch, fetch]
